name: Deploy Static PPT Hub to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Deploy entire project directory containing index.html, assets/
          branch: gh-pages # The target branch for GitHub Pages hosting
          clean: true # Keep old runs neat and tidy
